spring:
  application:
    name: crm
  jpa:
    open-in-view: false
  profiles:
    active:
      - dev
      - no-security
  kafka:
    consumer:
      group-id: crm-consumer
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: it.polito.wa2.g13.communication_manager.dtos
        spring.json.type.mapping: it.polito.wa2.g13.communication_manager.dtos.CreateMessageDTO:it.polito.wa2.g13.crm.dtos.CreateMessageDTO

kafka-config:
  mail-topic: ${MAIL_TOPIC:mail.json}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true